# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a418205bae0b08f40ee080ec2e3059a633db807f9d9c23b4107bcad8bcf25eb44b9ff0aa5345ddf1728cf4103b4f83e1603d747ef2741813496e5a5b314a542

test:
  secret_key_base: 5255481e703ef7737b9ea6bffb4bd34123bd3541a80f6da3eb1a5dff715c97bd54bb02f844cc33bf81cadff4b57d5e248ba256ee3ceb2486a4d86dabfa143cdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
